# Generated by Django 4.1.1 on 2022-09-25 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionProductos', '0003_alter_product_price'),
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(through='carts.CartProducts', to='GestionProductos.product'),
        ),
    ]
