# Generated by Django 4.1.1 on 2022-09-20 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionProductos', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10, verbose_name='Precio'),
        ),
    ]
