# Generated by Django 4.1.1 on 2022-09-26 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionProductos', '0004_product_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterModelTable(
            name='product',
            table=None,
        ),
    ]
